PREFIX linkml: <https://w3id.org/linkml/>
PREFIX iso27001: <https://w3id.org/lmodel/iso27001/>
PREFIX iso27002: <https://w3id.org/lmodel/iso27002/>
PREFIX iso: <https://www.iso.org/standard/>
PREFIX schema: <http://schema.org/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX cis_controls: <https://w3id.org/lmodel/cis-controls/>
PREFIX oscal: <https://w3id.org/lmodel/oscal/>
PREFIX nist_sp_800_53: <https://w3id.org/lmodel/nist-sp-800-53/>
PREFIX nist_csf_v2: <https://w3id.org/lmodel/nist-csf-v2/>
PREFIX nist_sp_800_171: <https://w3id.org/lmodel/nist-sp-800-171/>
PREFIX nist_sp_800_218: <https://w3id.org/lmodel/nist-sp-800-218/>
PREFIX attack: <https://w3id.org/lmodel/attack/>
PREFIX d3f: <https://d3fend.mitre.org/ontologies/d3fend.owl#>
PREFIX slsa: <https://w3id.org/lmodel/slsa/>
PREFIX stix: <https://w3id.org/lmodel/stix/>
PREFIX ocsf: <https://w3id.org/lmodel/ocsf/>
PREFIX spdx: <https://w3id.org/lmodel/spdx/>
PREFIX capec: <https://w3id.org/lmodel/capec/>
PREFIX cwe: <https://w3id.org/lmodel/cwe/>
PREFIX cve: <https://w3id.org/lmodel/cve/>
PREFIX nvd: <https://w3id.org/lmodel/nist-nvd/>
PREFIX kev_catalog: <https://w3id.org/lmodel/kev-catalog/>
PREFIX iso29100: <https://w3id.org/lmodel/iso29100/>
PREFIX semapv: <https://w3id.org/semapv/vocab/>
PREFIX iso42001: <https://w3id.org/lmodel/iso42001/>

SELECT
  ?check
  ?graph
  ?subject
  ?predicate WHERE {
 GRAPH ?graph {
  ?subject rdf:type iso27001:InterestedParty .
  FILTER NOT EXISTS { ?subject  iso27001:id ?o  }
 }
 VALUES ?check { linkml:required }
 VALUES ?predicate { iso27001:id }
 
}  



