// Code generated by linkml-golanggen. DO NOT EDIT.
package iso27001

import (
	"time"
)
// The four control domains defined in ISO/IEC 27001:2022 Annex A, corresponding to Clauses 5-8 of ISO/IEC 27002:2022.
type ControlCategory string

const (
	// Organizational controls (Annex A.5) - policies, roles, asset management, access control, supplier relationships, incident management, compliance.
	ControlCategoryOrganizational ControlCategory = "organizational"
	// People controls (Annex A.6) - screening, employment terms, awareness, disciplinary process, termination responsibilities, remote working.
	ControlCategoryPeople ControlCategory = "people"
	// Physical controls (Annex A.7) - perimeters, entry controls, equipment protection, secure areas, media handling, cabling, maintenance.
	ControlCategoryPhysical ControlCategory = "physical"
	// Technological controls (Annex A.8) - endpoint security, access restrictions, authentication, malware protection, logging, cryptography, secure development.
	ControlCategoryTechnological ControlCategory = "technological"
)
// Lifecycle status of a security control, used in Statement of Applicability and control tracking.
type ImplementationStatus string

const (
	// Control identified but no implementation activities begun.
	ImplementationStatusNotStarted ImplementationStatus = "not_started"
	// Control scheduled for implementation with defined timeline.
	ImplementationStatusPlanned ImplementationStatus = "planned"
	// Implementation actively underway but not yet complete.
	ImplementationStatusInProgress ImplementationStatus = "in_progress"
	// Control fully implemented and operational.
	ImplementationStatusImplemented ImplementationStatus = "implemented"
	// Control excluded from scope with documented justification per 6.1.3 d).
	ImplementationStatusNotApplicable ImplementationStatus = "not_applicable"
)
// Standard risk treatment options per ISO 31000 and ISO 27005.
type RiskTreatmentOption string

const (
	// Apply controls to change the risk level (reduce likelihood or impact).
	RiskTreatmentOptionModify RiskTreatmentOption = "modify"
	// Accept the risk without further treatment, within risk appetite. Requires risk owner approval.
	RiskTreatmentOptionAccept RiskTreatmentOption = "accept"
	// Eliminate the risk by removing the activity or asset that creates it.
	RiskTreatmentOptionAvoid RiskTreatmentOption = "avoid"
	// Transfer or share risk with external parties (e.g., insurance, outsourcing).
	RiskTreatmentOptionShare RiskTreatmentOption = "share"
)
// Qualitative risk rating derived from likelihood x impact analysis.
type RiskLevel string

const (
	// Negligible risk requiring no immediate action.
	RiskLevelVeryLow RiskLevel = "very_low"
	// Minor risk manageable through routine procedures.
	RiskLevelLow RiskLevel = "low"
	// Moderate risk requiring management attention and planned controls.
	RiskLevelMedium RiskLevel = "medium"
	// Significant risk requiring priority treatment and escalation.
	RiskLevelHigh RiskLevel = "high"
	// Severe risk threatening organizational objectives; requires immediate executive action and resource allocation.
	RiskLevelCritical RiskLevel = "critical"
)
// Categories of documented information required or recommended by ISO 27001.
type DocumentType string

const (
	// High-level statement of intent and direction (e.g., IS policy per 5.2).
	DocumentTypePolicy DocumentType = "policy"
	// Documented steps for performing activities consistently.
	DocumentTypeProcedure DocumentType = "procedure"
	// Mandatory requirements for specific technologies or processes.
	DocumentTypeStandard DocumentType = "standard"
	// Recommended practices that support policies and procedures.
	DocumentTypeGuideline DocumentType = "guideline"
	// Evidence of activities performed or results achieved.
	DocumentTypeRecord DocumentType = "record"
	// Documented approach for achieving objectives (e.g., risk treatment plan).
	DocumentTypePlan DocumentType = "plan"
	// Formal output of assessment, audit, or review activities.
	DocumentTypeReport DocumentType = "report"
)
// Classification of internal audit findings.
type AuditFindingType string

const (
	// Significant failure to fulfill a requirement that affects ISMS capability to achieve intended outcomes.
	AuditFindingTypeMajorNonconformity AuditFindingType = "major_nonconformity"
	// Isolated lapse that does not significantly affect ISMS effectiveness.
	AuditFindingTypeMinorNonconformity AuditFindingType = "minor_nonconformity"
	// Noted condition that could lead to nonconformity if not addressed.
	AuditFindingTypeObservation AuditFindingType = "observation"
	// Evidence of effective implementation exceeding requirements.
	AuditFindingTypePositiveFinding AuditFindingType = "positive_finding"
)
// Qualitative likelihood scale for risk assessment.
type LikelihoodRating string

const (
	// Highly unlikely to occur (< 5% probability).
	LikelihoodRatingRare LikelihoodRating = "rare"
	// Not expected but possible (5-20% probability).
	LikelihoodRatingUnlikely LikelihoodRating = "unlikely"
	// May occur at some point (20-50% probability).
	LikelihoodRatingPossible LikelihoodRating = "possible"
	// Probably will occur (50-80% probability).
	LikelihoodRatingLikely LikelihoodRating = "likely"
	// Expected to occur in most circumstances (> 80% probability).
	LikelihoodRatingAlmostCertain LikelihoodRating = "almost_certain"
)
// Information security properties whose loss is considered when identifying risks per ISO/IEC 27001:2022 Clause 6.1.2 c) 1).
type CIAProperty string

const (
	// Property of information not being made available or disclosed to unauthorized entities.
	CIAPropertyConfidentiality CIAProperty = "confidentiality"
	// Property of accuracy and completeness of information.
	CIAPropertyIntegrity CIAProperty = "integrity"
	// Property of being accessible and usable on demand by an authorized entity.
	CIAPropertyAvailability CIAProperty = "availability"
)
// Classification of audits referenced by ISO/IEC 27001:2022 Clause 9.2 and ISO/IEC 17021-1 (audit programmes).
type AuditType string

const (
	// First-party audit conducted by the organization itself per 9.2.
	AuditTypeInternal AuditType = "internal"
	// Audit conducted by a party with an interest in the organization (e.g., customer).
	AuditTypeExternalSecondParty AuditType = "external_second_party"
	// Independent audit by a certification body or other third party.
	AuditTypeExternalThirdParty AuditType = "external_third_party"
	// Periodic third-party audit between certification and recertification.
	AuditTypeSurveillance AuditType = "surveillance"
	// Third-party audit conducted to renew certification.
	AuditTypeRecertification AuditType = "recertification"
	// Audit performed jointly against two or more management system standards.
	AuditTypeCombined AuditType = "combined"
)
// Identifiers of the 93 reference information security controls listed in ISO/IEC 27001:2022 Annex A (as also titled in ISO/IEC 27002:2022). Control text and titles are normative ISO content and are not reproduced here.
type AnnexAControlId string

const (
	AnnexAControlIdA51 AnnexAControlId = "a_5_1"
	AnnexAControlIdA52 AnnexAControlId = "a_5_2"
	AnnexAControlIdA53 AnnexAControlId = "a_5_3"
	AnnexAControlIdA54 AnnexAControlId = "a_5_4"
	AnnexAControlIdA55 AnnexAControlId = "a_5_5"
	AnnexAControlIdA56 AnnexAControlId = "a_5_6"
	AnnexAControlIdA57 AnnexAControlId = "a_5_7"
	AnnexAControlIdA58 AnnexAControlId = "a_5_8"
	AnnexAControlIdA59 AnnexAControlId = "a_5_9"
	AnnexAControlIdA510 AnnexAControlId = "a_5_10"
	AnnexAControlIdA511 AnnexAControlId = "a_5_11"
	AnnexAControlIdA512 AnnexAControlId = "a_5_12"
	AnnexAControlIdA513 AnnexAControlId = "a_5_13"
	AnnexAControlIdA514 AnnexAControlId = "a_5_14"
	AnnexAControlIdA515 AnnexAControlId = "a_5_15"
	AnnexAControlIdA516 AnnexAControlId = "a_5_16"
	AnnexAControlIdA517 AnnexAControlId = "a_5_17"
	AnnexAControlIdA518 AnnexAControlId = "a_5_18"
	AnnexAControlIdA519 AnnexAControlId = "a_5_19"
	AnnexAControlIdA520 AnnexAControlId = "a_5_20"
	AnnexAControlIdA521 AnnexAControlId = "a_5_21"
	AnnexAControlIdA522 AnnexAControlId = "a_5_22"
	AnnexAControlIdA523 AnnexAControlId = "a_5_23"
	AnnexAControlIdA524 AnnexAControlId = "a_5_24"
	AnnexAControlIdA525 AnnexAControlId = "a_5_25"
	AnnexAControlIdA526 AnnexAControlId = "a_5_26"
	AnnexAControlIdA527 AnnexAControlId = "a_5_27"
	AnnexAControlIdA528 AnnexAControlId = "a_5_28"
	AnnexAControlIdA529 AnnexAControlId = "a_5_29"
	AnnexAControlIdA530 AnnexAControlId = "a_5_30"
	AnnexAControlIdA531 AnnexAControlId = "a_5_31"
	AnnexAControlIdA532 AnnexAControlId = "a_5_32"
	AnnexAControlIdA533 AnnexAControlId = "a_5_33"
	AnnexAControlIdA534 AnnexAControlId = "a_5_34"
	AnnexAControlIdA535 AnnexAControlId = "a_5_35"
	AnnexAControlIdA536 AnnexAControlId = "a_5_36"
	AnnexAControlIdA537 AnnexAControlId = "a_5_37"
	AnnexAControlIdA61 AnnexAControlId = "a_6_1"
	AnnexAControlIdA62 AnnexAControlId = "a_6_2"
	AnnexAControlIdA63 AnnexAControlId = "a_6_3"
	AnnexAControlIdA64 AnnexAControlId = "a_6_4"
	AnnexAControlIdA65 AnnexAControlId = "a_6_5"
	AnnexAControlIdA66 AnnexAControlId = "a_6_6"
	AnnexAControlIdA67 AnnexAControlId = "a_6_7"
	AnnexAControlIdA68 AnnexAControlId = "a_6_8"
	AnnexAControlIdA71 AnnexAControlId = "a_7_1"
	AnnexAControlIdA72 AnnexAControlId = "a_7_2"
	AnnexAControlIdA73 AnnexAControlId = "a_7_3"
	AnnexAControlIdA74 AnnexAControlId = "a_7_4"
	AnnexAControlIdA75 AnnexAControlId = "a_7_5"
	AnnexAControlIdA76 AnnexAControlId = "a_7_6"
	AnnexAControlIdA77 AnnexAControlId = "a_7_7"
	AnnexAControlIdA78 AnnexAControlId = "a_7_8"
	AnnexAControlIdA79 AnnexAControlId = "a_7_9"
	AnnexAControlIdA710 AnnexAControlId = "a_7_10"
	AnnexAControlIdA711 AnnexAControlId = "a_7_11"
	AnnexAControlIdA712 AnnexAControlId = "a_7_12"
	AnnexAControlIdA713 AnnexAControlId = "a_7_13"
	AnnexAControlIdA714 AnnexAControlId = "a_7_14"
	AnnexAControlIdA81 AnnexAControlId = "a_8_1"
	AnnexAControlIdA82 AnnexAControlId = "a_8_2"
	AnnexAControlIdA83 AnnexAControlId = "a_8_3"
	AnnexAControlIdA84 AnnexAControlId = "a_8_4"
	AnnexAControlIdA85 AnnexAControlId = "a_8_5"
	AnnexAControlIdA86 AnnexAControlId = "a_8_6"
	AnnexAControlIdA87 AnnexAControlId = "a_8_7"
	AnnexAControlIdA88 AnnexAControlId = "a_8_8"
	AnnexAControlIdA89 AnnexAControlId = "a_8_9"
	AnnexAControlIdA810 AnnexAControlId = "a_8_10"
	AnnexAControlIdA811 AnnexAControlId = "a_8_11"
	AnnexAControlIdA812 AnnexAControlId = "a_8_12"
	AnnexAControlIdA813 AnnexAControlId = "a_8_13"
	AnnexAControlIdA814 AnnexAControlId = "a_8_14"
	AnnexAControlIdA815 AnnexAControlId = "a_8_15"
	AnnexAControlIdA816 AnnexAControlId = "a_8_16"
	AnnexAControlIdA817 AnnexAControlId = "a_8_17"
	AnnexAControlIdA818 AnnexAControlId = "a_8_18"
	AnnexAControlIdA819 AnnexAControlId = "a_8_19"
	AnnexAControlIdA820 AnnexAControlId = "a_8_20"
	AnnexAControlIdA821 AnnexAControlId = "a_8_21"
	AnnexAControlIdA822 AnnexAControlId = "a_8_22"
	AnnexAControlIdA823 AnnexAControlId = "a_8_23"
	AnnexAControlIdA824 AnnexAControlId = "a_8_24"
	AnnexAControlIdA825 AnnexAControlId = "a_8_25"
	AnnexAControlIdA826 AnnexAControlId = "a_8_26"
	AnnexAControlIdA827 AnnexAControlId = "a_8_27"
	AnnexAControlIdA828 AnnexAControlId = "a_8_28"
	AnnexAControlIdA829 AnnexAControlId = "a_8_29"
	AnnexAControlIdA830 AnnexAControlId = "a_8_30"
	AnnexAControlIdA831 AnnexAControlId = "a_8_31"
	AnnexAControlIdA832 AnnexAControlId = "a_8_32"
	AnnexAControlIdA833 AnnexAControlId = "a_8_33"
	AnnexAControlIdA834 AnnexAControlId = "a_8_34"
)
// Categories of information security incident used to classify events and incidents per ISO/IEC 27001:2022 Annex A controls A.5.24-A.5.28 and ISO/IEC 27035 incident management guidance.
type SecurityIncidentCategory string

const (
	// Malicious software, including viruses, worms, trojans, and ransomware.
	SecurityIncidentCategoryMalware SecurityIncidentCategory = "malware"
	// Malware encrypting or exfiltrating data for extortion.
	SecurityIncidentCategoryRansomware SecurityIncidentCategory = "ransomware"
	// Social-engineering attempt to obtain credentials or trigger malicious action.
	SecurityIncidentCategoryPhishing SecurityIncidentCategory = "phishing"
	// Manipulation of people to disclose information or perform unsafe actions.
	SecurityIncidentCategorySocialEngineering SecurityIncidentCategory = "social_engineering"
	// Access to systems or data by a party without authorization.
	SecurityIncidentCategoryUnauthorizedAccess SecurityIncidentCategory = "unauthorized_access"
	// Unauthorized control of a legitimate user or service account.
	SecurityIncidentCategoryAccountCompromise SecurityIncidentCategory = "account_compromise"
	// Authorized user exceeding or misusing their granted privileges.
	SecurityIncidentCategoryPrivilegeMisuse SecurityIncidentCategory = "privilege_misuse"
	// Confirmed disclosure of confidential or personal information.
	SecurityIncidentCategoryDataBreach SecurityIncidentCategory = "data_breach"
	// Loss of integrity or availability of information, including accidental deletion.
	SecurityIncidentCategoryDataLoss SecurityIncidentCategory = "data_loss"
	// Disruption of availability through volumetric, protocol, or application attacks.
	SecurityIncidentCategoryDenialOfService SecurityIncidentCategory = "denial_of_service"
	// Attack targeting a web application (e.g., injection, XSS, broken auth).
	SecurityIncidentCategoryWebApplicationAttack SecurityIncidentCategory = "web_application_attack"
	// Incident originating from a supplier, partner, or third-party component.
	SecurityIncidentCategorySupplyChain SecurityIncidentCategory = "supply_chain"
	// Malicious or negligent action by an internal party.
	SecurityIncidentCategoryInsiderThreat SecurityIncidentCategory = "insider_threat"
	// Theft, loss, or damage of physical assets or unauthorized physical access.
	SecurityIncidentCategoryPhysicalSecurity SecurityIncidentCategory = "physical_security"
	// Misconfiguration leading to security exposure.
	SecurityIncidentCategoryConfigurationError SecurityIncidentCategory = "configuration_error"
	// Weak, broken, or misused cryptography.
	SecurityIncidentCategoryCryptographicFailure SecurityIncidentCategory = "cryptographic_failure"
	// Failure to comply with information security policies or procedures.
	SecurityIncidentCategoryPolicyViolation SecurityIncidentCategory = "policy_violation"
	// Other incident type not covered by the listed categories.
	SecurityIncidentCategoryOther SecurityIncidentCategory = "other"
)
// Other ISO/IEC management system standards with which the ISMS may be integrated or aligned (e.g., harmonized structure of Annex SL).
type RelatedManagementSystem string

const (
	// Information security management systems.
	RelatedManagementSystemIsoIec27001 RelatedManagementSystem = "iso_iec_27001"
	// Privacy information management systems (PIMS).
	RelatedManagementSystemIsoIec27701 RelatedManagementSystem = "iso_iec_27701"
	// Information security for cloud services.
	RelatedManagementSystemIsoIec27017 RelatedManagementSystem = "iso_iec_27017"
	// Protection of personally identifiable information in public clouds.
	RelatedManagementSystemIsoIec27018 RelatedManagementSystem = "iso_iec_27018"
	// Artificial intelligence management systems.
	RelatedManagementSystemIsoIec42001 RelatedManagementSystem = "iso_iec_42001"
	// Quality management systems.
	RelatedManagementSystemIso9001 RelatedManagementSystem = "iso_9001"
	// Environmental management systems.
	RelatedManagementSystemIso14001 RelatedManagementSystem = "iso_14001"
	// Business continuity management systems.
	RelatedManagementSystemIso22301 RelatedManagementSystem = "iso_22301"
	// IT service management systems.
	RelatedManagementSystemIsoIec200001 RelatedManagementSystem = "iso_iec_20000_1"
	// Risk management - guidelines.
	RelatedManagementSystemIso31000 RelatedManagementSystem = "iso_31000"
)
// Qualitative impact scale for risk assessment.
type ImpactRating string

const (
	// No significant impact on operations or objectives.
	ImpactRatingNegligible ImpactRating = "negligible"
	// Limited impact, easily absorbed by normal operations.
	ImpactRatingMinor ImpactRating = "minor"
	// Noticeable impact requiring management intervention.
	ImpactRatingModerate ImpactRating = "moderate"
	// Serious impact on objectives, reputation, or compliance.
	ImpactRatingMajor ImpactRating = "major"
	// Catastrophic impact threatening organizational viability.
	ImpactRatingSevere ImpactRating = "severe"
)
// Abstract base class for all entities with an identifier, name, and description. Provides common identification and documentation slots.
type NamedEntity struct {
	// Unique identifier for this entity instance.
	Id string `json:"id"`
	// Human-readable name or title.
	Name string `json:"name"`
	// Detailed description of the entity.
	Description *string `json:"description,omitempty"`
	// Date when the entity was created.
	CreatedDate *time.Time `json:"created_date,omitempty"`
	// Date when the entity was last modified.
	ModifiedDate *time.Time `json:"modified_date,omitempty"`
	// Version identifier for the entity.
	Version *string `json:"version,omitempty"`
}

// Abstract class for documented information per Clause 7.5. Captures metadata required for document control.
type DocumentedInformation struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Classification of the documented information.
	DocumentType DocumentType `json:"document_type,omitempty"`
	// Unique reference number for document control.
	DocumentReference *string `json:"document_reference,omitempty"`
	// Person who created the document.
	Author *string `json:"author,omitempty"`
	// Person accountable for the document content and maintenance.
	Owner *string `json:"owner,omitempty"`
	// Person who approved the document.
	ApprovedBy *string `json:"approved_by,omitempty"`
	// Date when the document was approved.
	ApprovedDate *time.Time `json:"approved_date,omitempty"`
	// Date when the document becomes effective.
	EffectiveDate *time.Time `json:"effective_date,omitempty"`
	// Date when the document is due for review.
	ReviewDate *time.Time `json:"review_date,omitempty"`
	// Current status of the document or entity.
	Status *string `json:"status,omitempty"`
	// Information classification level.
	Classification *string `json:"classification,omitempty"`
	// Duration for which the document is retained.
	RetentionPeriod *string `json:"retention_period,omitempty"`
	// Controls governing distribution, access, retrieval and use of the documented information, per Clause 7.5.3 c).
	DistributionControls []string `json:"distribution_controls,omitempty"`
	// Arrangements for storage and preservation (including preservation of legibility) of the documented information, per Clause 7.5.3 d).
	StorageAndPreservation *string `json:"storage_and_preservation,omitempty"`
	// Method used for control of changes (e.g., version control) of the documented information, per Clause 7.5.3 e).
	ChangeControlMethod *string `json:"change_control_method,omitempty"`
	// Whether the documented information is of external origin and has been identified as necessary for the planning and operation of the ISMS, per Clause 7.5.3.
	ExternalOrigin *bool `json:"external_origin,omitempty"`
	// Source or provider of the externally originated documented information, per Clause 7.5.3.
	ExternalOriginSource *string `json:"external_origin_source,omitempty"`
}

// Top-level container representing an organization's complete ISMS per ISO 27001. Aggregates all components required to support the full ISMS lifecycle.
type InformationSecurityManagementSystem struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Reference to the organization operating the ISMS.
	Organization *OrganizationId `json:"organization,omitempty"`
	// The person or group of people who direct and control the organization at the highest level, accountable for the ISMS per Clause 5.1.
	TopManagement *string `json:"top_management,omitempty"`
	// The governing body to which top management reports, where applicable (e.g., board of directors). Referenced in ISO/IEC 27001:2022 Clause 5.1 NOTE.
	GoverningBody *string `json:"governing_body,omitempty"`
	// Evidence of leadership and commitment with respect to the ISMS as required by Clause 5.1 a-h).
	LeadershipCommitmentEvidence []string `json:"leadership_commitment_evidence,omitempty"`
	// Documented statement of ISMS scope per 4.3.
	ScopeStatement *string `json:"scope_statement,omitempty"`
	// Defined boundaries of the ISMS scope.
	ScopeBoundaries []string `json:"scope_boundaries,omitempty"`
	// Any exclusions from scope with justification.
	ScopeExclusions []string `json:"scope_exclusions,omitempty"`
	// Interfaces and dependencies between activities performed by the organization and those performed by other organizations, considered when determining the ISMS scope per Clause 4.3 c).
	InterfacesAndDependencies []string `json:"interfaces_and_dependencies,omitempty"`
	// Description of the processes needed for the ISMS and their interactions, per Clause 4.4.
	ProcessesAndInteractions *string `json:"processes_and_interactions,omitempty"`
	// Internal issues relevant to ISMS per 4.1.
	ContextInternalIssues []string `json:"context_internal_issues,omitempty"`
	// External issues relevant to ISMS per 4.1.
	ContextExternalIssues []string `json:"context_external_issues,omitempty"`
	// Stakeholders relevant to the ISMS.
	InterestedParties []InterestedPartyId `json:"interested_parties,omitempty"`
	// Reference to the information security policy.
	InformationSecurityPolicy *InformationSecurityPolicyId `json:"information_security_policy,omitempty"`
	// Information security objectives.
	Objectives []InformationSecurityObjectiveId `json:"objectives,omitempty"`
	// Actions to address risks and opportunities determined per Clause 6.1.1, including how they are integrated into ISMS processes and how their effectiveness is evaluated.
	RisksAndOpportunitiesActions []string `json:"risks_and_opportunities_actions,omitempty"`
	// Changes to the ISMS planned and controlled per Clause 6.3 and 8.1 (planning of changes; control of planned changes).
	PlannedChanges []string `json:"planned_changes,omitempty"`
	// Externally provided processes, products or services relevant to the ISMS that are controlled per Clause 8.1.
	ExternallyProvidedServices []string `json:"externally_provided_services,omitempty"`
	// Reference to the risk assessment process.
	RiskAssessmentProcess *RiskAssessmentProcessId `json:"risk_assessment_process,omitempty"`
	// Reference to the risk treatment process.
	RiskTreatmentProcess *RiskTreatmentProcessId `json:"risk_treatment_process,omitempty"`
	// Reference to the Statement of Applicability.
	StatementOfApplicability *StatementOfApplicabilityId `json:"statement_of_applicability,omitempty"`
	// Security controls applied in the ISMS.
	Controls []SecurityControlId `json:"controls,omitempty"`
	// Information security roles defined in the ISMS.
	Roles []RoleId `json:"roles,omitempty"`
	// Resources provided for the ISMS.
	Resources []ResourceId `json:"resources,omitempty"`
	// Competence records for personnel.
	CompetenceRecords []CompetenceRecordId `json:"competence_records,omitempty"`
	// Reference to the awareness program.
	AwarenessProgram *AwarenessProgramId `json:"awareness_program,omitempty"`
	// Reference to the communication plan.
	CommunicationPlan *CommunicationPlanId `json:"communication_plan,omitempty"`
	// Register of documented information.
	DocumentedInformationRegister []DocumentedInformationId `json:"documented_information_register,omitempty"`
	// Operational procedures.
	OperationalProcedures []OperationalProcedureId `json:"operational_procedures,omitempty"`
	// Risk assessment instances.
	RiskAssessments []RiskAssessmentId `json:"risk_assessments,omitempty"`
	// Risk treatment plans.
	RiskTreatmentPlans []RiskTreatmentPlanId `json:"risk_treatment_plans,omitempty"`
	// Reference to the monitoring program.
	MonitoringProgram *MonitoringProgramId `json:"monitoring_program,omitempty"`
	// Internal audit instances.
	InternalAudits []InternalAuditId `json:"internal_audits,omitempty"`
	// Management review instances.
	ManagementReviews []ManagementReviewId `json:"management_reviews,omitempty"`
	// Nonconformities identified.
	Nonconformities []NonconformityId `json:"nonconformities,omitempty"`
	// Corrective actions.
	CorrectiveActions []CorrectiveActionId `json:"corrective_actions,omitempty"`
	// Improvement opportunities tracked.
	Improvements []ImprovementOpportunityId `json:"improvements,omitempty"`
	// Current certification status.
	CertificationStatus *string `json:"certification_status,omitempty"`
	// Accredited certification body.
	CertificationBody *string `json:"certification_body,omitempty"`
	// Date certification was achieved.
	CertificationDate *time.Time `json:"certification_date,omitempty"`
	// Date recertification is due.
	RecertificationDate *time.Time `json:"recertification_date,omitempty"`
}

// The organization establishing and operating the ISMS. Captures context needed for Clause 4.1 (understanding the organization).
type Organization struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Legal registered name of the organization.
	LegalName *string `json:"legal_name,omitempty"`
	// Names under which the organization conducts business.
	TradingNames []string `json:"trading_names,omitempty"`
	// Type of organization (e.g., corporation, government, nonprofit).
	OrganizationType *string `json:"organization_type,omitempty"`
	// Primary industry sector of the organization.
	IndustrySector *string `json:"industry_sector,omitempty"`
	// Organization size classification.
	SizeCategory *string `json:"size_category,omitempty"`
	// Approximate number of employees.
	EmployeeCount *int `json:"employee_count,omitempty"`
	// Countries or regions where the organization operates.
	GeographicLocations []string `json:"geographic_locations,omitempty"`
	// Jurisdictions whose regulations apply to the organization.
	RegulatoryJurisdictions []string `json:"regulatory_jurisdictions,omitempty"`
	// Parent organization if applicable.
	ParentOrganization *string `json:"parent_organization,omitempty"`
	// Subsidiary organizations if applicable.
	Subsidiaries []string `json:"subsidiaries,omitempty"`
	// Whether climate change has been determined to be a relevant issue for the organization's context, per Clause 4.1 as amended by Amd. 1:2024.
	ClimateChangeRelevant *bool `json:"climate_change_relevant,omitempty"`
}

// A stakeholder whose needs and expectations are relevant to the ISMS per 4.2. Includes internal parties (employees, management) and external parties (customers, regulators, suppliers).
type InterestedParty struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Category of interested party.
	PartyType *string `json:"party_type,omitempty"`
	// Nature of the relationship with the organization.
	Relationship *string `json:"relationship,omitempty"`
	// Requirements of the interested party.
	Requirements []string `json:"requirements,omitempty"`
	// Requirements of the interested party that the organization has determined will be addressed through the ISMS, per Clause 4.2 c).
	AddressedRequirements []string `json:"addressed_requirements,omitempty"`
	// Climate-change-related requirements of the interested party, per ISO/IEC 27001:2022 Clause 4.2 NOTE 2 as added by Amd. 1:2024.
	ClimateChangeRelatedRequirements []string `json:"climate_change_related_requirements,omitempty"`
	// Communication requirements for this party.
	CommunicationNeeds *string `json:"communication_needs,omitempty"`
	// Contact details for the party.
	ContactInformation *string `json:"contact_information,omitempty"`
}

// The information security policy established by top management per Clause 5.2. Provides framework for setting objectives and demonstrates commitment.
type InformationSecurityPolicy struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// The core policy statement text.
	PolicyStatement *string `json:"policy_statement,omitempty"`
	// Framework for setting information security objectives.
	PolicyObjectivesFramework *string `json:"policy_objectives_framework,omitempty"`
	// Statements of commitment included in the policy.
	CommitmentStatements []string `json:"commitment_statements,omitempty"`
	// Statement of policy applicability.
	ApplicabilityStatement *string `json:"applicability_statement,omitempty"`
	// Date when the policy was communicated.
	CommunicationDate *time.Time `json:"communication_date,omitempty"`
	// Whether acknowledgment is required from personnel.
	AcknowledgmentRequired *bool `json:"acknowledgment_required,omitempty"`
	// Date of the most recent information security policy review.
	LastPolicyReviewDate *time.Time `json:"last_policy_review_date,omitempty"`
	// Planned date of the next information security policy review.
	NextPolicyReviewDate *time.Time `json:"next_policy_review_date,omitempty"`
	// Topic-specific policies supporting this policy.
	RelatedTopicPolicies []TopicSpecificPolicyId `json:"related_topic_policies,omitempty"`
	// Other ISO/IEC management system standards with which the ISMS is integrated or aligned (per the harmonized structure of Annex SL).
	IntegratedManagementSystems []RelatedManagementSystem `json:"integrated_management_systems,omitempty"`
}

// A policy addressing a specific information security topic, supporting the overarching information security policy.
type TopicSpecificPolicy struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// The specific topic addressed by the policy.
	TopicArea *string `json:"topic_area,omitempty"`
	// The parent policy this topic-specific policy supports.
	ParentPolicy *InformationSecurityPolicyId `json:"parent_policy,omitempty"`
	// Controls related to this policy.
	ApplicableControls []SecurityControlId `json:"applicable_controls,omitempty"`
	// Intended audience for the policy or document.
	TargetAudience *string `json:"target_audience,omitempty"`
}

// An information security role with defined responsibilities and authorities per Clause 5.3.
type Role struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Category of the role.
	RoleType *string `json:"role_type,omitempty"`
	// Responsibilities assigned to the role.
	Responsibilities []string `json:"responsibilities,omitempty"`
	// Authorities granted to the role.
	Authorities []string `json:"authorities,omitempty"`
	// What the role is accountable for.
	Accountability *string `json:"accountability,omitempty"`
	// Person(s) assigned to this role.
	AssignedTo []string `json:"assigned_to,omitempty"`
	// Rules for delegating responsibilities.
	DelegationRules *string `json:"delegation_rules,omitempty"`
	// To whom this role reports.
	ReportingLine *string `json:"reporting_line,omitempty"`
}

// A measurable information security objective per Clause 6.2, established at relevant functions and levels of the organization.
type InformationSecurityObjective struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Clear statement of the objective.
	ObjectiveStatement *string `json:"objective_statement,omitempty"`
	// Target value for the objective metric.
	TargetValue *string `json:"target_value,omitempty"`
	// Current measured value.
	CurrentValue *string `json:"current_value,omitempty"`
	// Definition of how the objective is measured.
	MetricDefinition *string `json:"metric_definition,omitempty"`
	// Method used to measure the metric.
	MeasurementMethod *string `json:"measurement_method,omitempty"`
	// How often measurement is performed.
	MeasurementFrequency *string `json:"measurement_frequency,omitempty"`
	// Role responsible for the objective or control.
	ResponsibleRole *RoleId `json:"responsible_role,omitempty"`
	// Target date for achieving the objective.
	TargetDate *time.Time `json:"target_date,omitempty"`
	// Current status of objective achievement.
	AchievementStatus *string `json:"achievement_status,omitempty"`
	// Associated risks.
	RelatedRisks []RiskId `json:"related_risks,omitempty"`
	// Other controls related to this one.
	RelatedControls []SecurityControlId `json:"related_controls,omitempty"`
	// Plan for achieving the objective.
	ActionPlan *string `json:"action_plan,omitempty"`
	// Resources required to achieve the information security objective.
	ObjectiveResourcesRequired *string `json:"objective_resources_required,omitempty"`
}

// The documented risk assessment process per Clause 6.1.2, defining criteria and methodology for identifying, analyzing, and evaluating risks.
type RiskAssessmentProcess struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Criteria for accepting risks.
	RiskAcceptanceCriteria *string `json:"risk_acceptance_criteria,omitempty"`
	// Criteria for performing risk assessments.
	AssessmentCriteria *string `json:"assessment_criteria,omitempty"`
	// Methodology used for risk assessment.
	AssessmentMethodology *string `json:"assessment_methodology,omitempty"`
	// Scale used for likelihood rating.
	LikelihoodScale *string `json:"likelihood_scale,omitempty"`
	// Scale used for impact rating.
	ImpactScale *string `json:"impact_scale,omitempty"`
	// Risk matrix or calculation method.
	RiskMatrix *string `json:"risk_matrix,omitempty"`
	// Planned frequency of risk assessments.
	AssessmentFrequency *string `json:"assessment_frequency,omitempty"`
	// Events that trigger risk assessment outside planned schedule.
	TriggerEvents []string `json:"trigger_events,omitempty"`
}

// An instance of risk assessment performed per Clause 8.2, identifying and evaluating information security risks.
type RiskAssessment struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Scope of the assessment.
	AssessmentScope *string `json:"assessment_scope,omitempty"`
	// Date the assessment was conducted.
	AssessmentDate *time.Time `json:"assessment_date,omitempty"`
	// Person or team who conducted the assessment.
	Assessor *string `json:"assessor,omitempty"`
	// Specific methodology applied in this assessment.
	MethodologyUsed *string `json:"methodology_used,omitempty"`
	// Risks identified in this assessment.
	RisksIdentified []RiskId `json:"risks_identified,omitempty"`
	// Summary of assessment findings.
	SummaryFindings *string `json:"summary_findings,omitempty"`
	// Recommendations from the assessment.
	Recommendations []string `json:"recommendations,omitempty"`
	// Planned date for next assessment.
	NextAssessmentDate *time.Time `json:"next_assessment_date,omitempty"`
}

// An identified information security risk that may affect information security properties within the ISMS scope.
type Risk struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Source or origin of the risk.
	RiskSource *string `json:"risk_source,omitempty"`
	// Description of the threat exploiting the vulnerability.
	ThreatDescription *string `json:"threat_description,omitempty"`
	// Description of the vulnerability that could be exploited.
	VulnerabilityDescription *string `json:"vulnerability_description,omitempty"`
	// Assets affected by this risk or incident.
	AffectedAssets []AssetId `json:"affected_assets,omitempty"`
	// Which CIA properties are affected (confidentiality, integrity, availability).
	AffectedCiaProperties []CIAProperty `json:"affected_cia_properties,omitempty"`
	// Person accountable for managing the risk.
	RiskOwner *string `json:"risk_owner,omitempty"`
	// Assessed likelihood of risk occurrence.
	Likelihood LikelihoodRating `json:"likelihood,omitempty"`
	// Assessed impact if risk materializes.
	Impact ImpactRating `json:"impact,omitempty"`
	// Risk level before controls are applied.
	InherentRiskLevel RiskLevel `json:"inherent_risk_level,omitempty"`
	// Controls currently in place affecting this risk.
	ExistingControls []SecurityControlId `json:"existing_controls,omitempty"`
	// Risk level after controls are applied.
	ResidualRiskLevel RiskLevel `json:"residual_risk_level,omitempty"`
	// Selected treatment option for the risk.
	RiskTreatmentOption RiskTreatmentOption `json:"risk_treatment_option,omitempty"`
	// Priority for treating this risk.
	TreatmentPriority *string `json:"treatment_priority,omitempty"`
	// Risk treatment plan addressing this risk.
	RelatedTreatmentPlan *RiskTreatmentPlanId `json:"related_treatment_plan,omitempty"`
}

// The documented risk treatment process per Clause 6.1.3, defining how treatment options are selected and controls determined.
type RiskTreatmentProcess struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Guidance on selecting treatment options.
	TreatmentOptionsGuidance *string `json:"treatment_options_guidance,omitempty"`
	// Criteria for selecting controls.
	ControlSelectionCriteria *string `json:"control_selection_criteria,omitempty"`
	// Description of how controls determined as necessary are compared with those in Annex A to verify that no necessary controls have been omitted, per Clause 6.1.3 c).
	AnnexAOmissionVerification *string `json:"annex_a_omission_verification,omitempty"`
	// Template used for Statement of Applicability.
	SoaTemplate *string `json:"soa_template,omitempty"`
	// Workflow for approving risk treatment.
	ApprovalWorkflow *string `json:"approval_workflow,omitempty"`
}

// A risk treatment plan documenting planned actions to address identified risks through selected controls.
type RiskTreatmentPlan struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Scope of the plan.
	PlanScope *string `json:"plan_scope,omitempty"`
	// Risks addressed by this plan.
	RisksAddressed []RiskId `json:"risks_addressed,omitempty"`
	// Actions to be taken for treatment.
	TreatmentActions []string `json:"treatment_actions,omitempty"`
	// Controls to be implemented as part of treatment.
	ControlsToImplement []SecurityControlId `json:"controls_to_implement,omitempty"`
	// Resources required for implementation.
	ResourcesRequired *string `json:"resources_required,omitempty"`
	// Parties responsible for implementation.
	ResponsibleParties []string `json:"responsible_parties,omitempty"`
	// Timeline for implementation.
	ImplementationTimeline *string `json:"implementation_timeline,omitempty"`
	// Risk owner who approved the plan.
	RiskOwnerApproval *string `json:"risk_owner_approval,omitempty"`
	// Date when the risk treatment plan was approved.
	ApprovedDate *time.Time `json:"approved_date,omitempty"`
	// Documentation of residual risk acceptance.
	ResidualRiskAcceptance *string `json:"residual_risk_acceptance,omitempty"`
	// Current implementation status.
	ImplementationStatus ImplementationStatus `json:"implementation_status,omitempty"`
	// Date when implementation was completed.
	CompletionDate *time.Time `json:"completion_date,omitempty"`
}

// The Statement of Applicability (SoA) recording which controls apply, their rationale, and current implementation state.
type StatementOfApplicability struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Individual control entries in the SoA.
	SoaEntries []SoAEntry `json:"soa_entries,omitempty"`
	// Total number of controls in scope.
	TotalControls *int `json:"total_controls,omitempty"`
	// Number of implemented controls.
	ImplementedCount *int `json:"implemented_count,omitempty"`
	// Number of controls planned for implementation.
	PlannedCount *int `json:"planned_count,omitempty"`
	// Number of controls marked not applicable.
	NotApplicableCount *int `json:"not_applicable_count,omitempty"`
	// Date of last review.
	LastReviewDate *time.Time `json:"last_review_date,omitempty"`
	// Person who approved the document.
	ApprovedBy *string `json:"approved_by,omitempty"`
}

// A single entry in the Statement of Applicability, documenting the applicability and implementation status of one control.
type SoAEntry struct {
	// Reference to the control (e.g., A.5.1).
	ControlReference *SecurityControlId `json:"control_reference,omitempty"`
	// Whether the control is applicable.
	IsApplicable *bool `json:"is_applicable,omitempty"`
	// Justification for including the control.
	InclusionJustification *string `json:"inclusion_justification,omitempty"`
	// Justification for excluding the control.
	ExclusionJustification *string `json:"exclusion_justification,omitempty"`
	// Current implementation status.
	ImplementationStatus ImplementationStatus `json:"implementation_status,omitempty"`
	// Evidence of control implementation.
	ImplementationEvidence *string `json:"implementation_evidence,omitempty"`
	// Role responsible for the objective or control.
	ResponsibleRole *RoleId `json:"responsible_role,omitempty"`
	// Target date for implementing the control.
	TargetImplementationDate *time.Time `json:"target_implementation_date,omitempty"`
}

// A security control from Annex A of ISO/IEC 27001:2022, derived from ISO/IEC 27002:2022. Represents a measure that modifies risk.
type SecurityControl struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Control identifier from Annex A (e.g., a_5_1, a_8_24).
	ControlId AnnexAControlId `json:"control_id,omitempty"`
	// Title of the control.
	ControlTitle *string `json:"control_title,omitempty"`
	// Domain category of the control.
	ControlCategory ControlCategory `json:"control_category,omitempty"`
	// Organization-authored control statement or external control summary.
	ControlText *string `json:"control_text,omitempty"`
	// Organization-authored implementation notes for the control.
	ImplementationGuidance *string `json:"implementation_guidance,omitempty"`
	// Other controls related to this one.
	RelatedControls []SecurityControlId `json:"related_controls,omitempty"`
	// Threats this control addresses.
	ApplicableThreats []string `json:"applicable_threats,omitempty"`
	// Asset types this control applies to.
	ApplicableAssets []string `json:"applicable_assets,omitempty"`
	// Person responsible for the control.
	ControlOwner *string `json:"control_owner,omitempty"`
	// Current implementation status.
	ImplementationStatus ImplementationStatus `json:"implementation_status,omitempty"`
	// Date the control was implemented.
	ImplementationDate *time.Time `json:"implementation_date,omitempty"`
	// Rating of control effectiveness.
	EffectivenessRating *string `json:"effectiveness_rating,omitempty"`
	// Date the control was last tested.
	LastTestDate *time.Time `json:"last_test_date,omitempty"`
	// References to evidence of implementation.
	EvidenceReferences []string `json:"evidence_references,omitempty"`
}

// A resource provided for the ISMS per Clause 7.1, including personnel, infrastructure, technology, and budget.
type Resource struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Type of resource.
	ResourceType *string `json:"resource_type,omitempty"`
	// Quantity of the resource.
	Quantity *string `json:"quantity,omitempty"`
	// Date the resource was allocated.
	AllocationDate *time.Time `json:"allocation_date,omitempty"`
	// What the resource is allocated to.
	AllocatedTo *string `json:"allocated_to,omitempty"`
	// Cost of the resource.
	Cost *string `json:"cost,omitempty"`
	// Current availability of the resource.
	AvailabilityStatus *string `json:"availability_status,omitempty"`
}

// Evidence of competence for personnel affecting information security performance per Clause 7.2 d).
type CompetenceRecord struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Name of the person.
	PersonName *string `json:"person_name,omitempty"`
	// Role of the person.
	PersonRole *string `json:"person_role,omitempty"`
	// Competencies required for the role.
	RequiredCompetencies []string `json:"required_competencies,omitempty"`
	// Education qualifications.
	EducationRecords []string `json:"education_records,omitempty"`
	// Training completed.
	TrainingRecords []string `json:"training_records,omitempty"`
	// Relevant experience.
	ExperienceRecords []string `json:"experience_records,omitempty"`
	// Date of last competency assessment.
	CompetencyAssessmentDate *time.Time `json:"competency_assessment_date,omitempty"`
	// Identified competency gaps.
	CompetencyGaps []string `json:"competency_gaps,omitempty"`
	// Actions to address competency gaps.
	DevelopmentActions []string `json:"development_actions,omitempty"`
}

// The awareness program ensuring personnel understand their information security responsibilities per Clause 7.3.
type AwarenessProgram struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Topics covered in awareness program.
	AwarenessTopics []string `json:"awareness_topics,omitempty"`
	// Methods used to deliver awareness content.
	DeliveryMethods []string `json:"delivery_methods,omitempty"`
	// Intended audience for the policy or document.
	TargetAudience *string `json:"target_audience,omitempty"`
	// Frequency of the activity.
	Frequency *string `json:"frequency,omitempty"`
	// How completion is tracked.
	CompletionTracking *string `json:"completion_tracking,omitempty"`
	// How effectiveness is measured.
	EffectivenessMeasures *string `json:"effectiveness_measures,omitempty"`
}

// Plan for internal and external communications relevant to the ISMS per Clause 7.4.
type CommunicationPlan struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Communication items in the plan.
	CommunicationItems []CommunicationItem `json:"communication_items,omitempty"`
}

// A single communication requirement within the communication plan.
type CommunicationItem struct {
	// Subject of the communication.
	Subject *string `json:"subject,omitempty"`
	// Purpose of the communication.
	Purpose *string `json:"purpose,omitempty"`
	// Target audience.
	Audience *string `json:"audience,omitempty"`
	// Frequency of the activity.
	Frequency *string `json:"frequency,omitempty"`
	// Method of communication.
	Method *string `json:"method,omitempty"`
	// Party responsible for the activity.
	ResponsibleParty *string `json:"responsible_party,omitempty"`
	// Whether records are required.
	RecordsRequired *bool `json:"records_required,omitempty"`
}

// A documented procedure for operational planning and control per Clause 8.1.
type OperationalProcedure struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Scope of the procedure.
	ProcedureScope *string `json:"procedure_scope,omitempty"`
	// Criteria established for the process.
	ProcessCriteria *string `json:"process_criteria,omitempty"`
	// Control measures implemented.
	ControlMeasures []string `json:"control_measures,omitempty"`
	// Roles responsible for the procedure.
	ResponsibleRoles []RoleId `json:"responsible_roles,omitempty"`
	// Other controls related to this one.
	RelatedControls []SecurityControlId `json:"related_controls,omitempty"`
	// Requirements for controlling changes.
	ChangeControlRequirements *string `json:"change_control_requirements,omitempty"`
}

// The program for monitoring, measurement, analysis, and evaluation per Clause 9.1.
type MonitoringProgram struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Items to be monitored.
	MonitoringItems []MonitoringItem `json:"monitoring_items,omitempty"`
}

// A single item to be monitored and measured per 9.1.
type MonitoringItem struct {
	// Name of the metric.
	MetricName *string `json:"metric_name,omitempty"`
	// Description of what is measured.
	MetricDescription *string `json:"metric_description,omitempty"`
	// Method used to measure the metric.
	MeasurementMethod *string `json:"measurement_method,omitempty"`
	// How often measurement is performed.
	MeasurementFrequency *string `json:"measurement_frequency,omitempty"`
	// Party responsible for the activity.
	ResponsibleParty *string `json:"responsible_party,omitempty"`
	// How often analysis is performed.
	AnalysisFrequency *string `json:"analysis_frequency,omitempty"`
	// Person performing analysis.
	Analyst *string `json:"analyst,omitempty"`
	// Target threshold value.
	TargetThreshold *string `json:"target_threshold,omitempty"`
	// Threshold triggering alerts.
	AlertThreshold *string `json:"alert_threshold,omitempty"`
	// Current measured value.
	CurrentValue *string `json:"current_value,omitempty"`
	// Current trend direction.
	Trend *string `json:"trend,omitempty"`
}

// An internal audit instance per Clause 9.2, assessing ISMS conformance and effectiveness.
type InternalAudit struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Reference identifier for the audit.
	AuditReference *string `json:"audit_reference,omitempty"`
	// Type of audit per ISO/IEC 27001:2022 Clause 9.2 and ISO/IEC 17021-1.
	AuditType AuditType `json:"audit_type,omitempty"`
	// Scope of the audit.
	AuditScope *string `json:"audit_scope,omitempty"`
	// Criteria against which audit is conducted.
	AuditCriteria []string `json:"audit_criteria,omitempty"`
	// Objectives of the audit.
	AuditObjectives []string `json:"audit_objectives,omitempty"`
	// Start date of audit period.
	AuditPeriodStart *time.Time `json:"audit_period_start,omitempty"`
	// End date of audit period.
	AuditPeriodEnd *time.Time `json:"audit_period_end,omitempty"`
	// Lead auditor for the audit.
	LeadAuditor *string `json:"lead_auditor,omitempty"`
	// Audit team members.
	AuditTeam []string `json:"audit_team,omitempty"`
	// Representatives from audited areas.
	AuditeeRepresentatives []string `json:"auditee_representatives,omitempty"`
	// Audit plan document reference.
	AuditPlan *string `json:"audit_plan,omitempty"`
	// Audit findings.
	Findings []AuditFindingId `json:"findings,omitempty"`
	// Positive observations noted.
	PositiveObservations []string `json:"positive_observations,omitempty"`
	// Overall audit conclusion.
	AuditConclusion *string `json:"audit_conclusion,omitempty"`
	// Date the report was issued.
	ReportDate *time.Time `json:"report_date,omitempty"`
	// Distribution list for the report.
	ReportDistribution []string `json:"report_distribution,omitempty"`
}

// The internal audit programme per 9.2.2, planning audit activities over a defined period.
type AuditProgramme struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Period covered by the audit programme.
	ProgrammePeriod *string `json:"programme_period,omitempty"`
	// Audits planned in this programme.
	PlannedAudits []InternalAuditId `json:"planned_audits,omitempty"`
	// Rationale for audit frequency decisions.
	AuditFrequencyRationale *string `json:"audit_frequency_rationale,omitempty"`
	// Resource requirements for the programme.
	ResourceRequirements *string `json:"resource_requirements,omitempty"`
	// Required qualifications for auditors.
	AuditorQualifications *string `json:"auditor_qualifications,omitempty"`
	// Current status of the programme.
	ProgrammeStatus *string `json:"programme_status,omitempty"`
}

// A finding from an internal audit, including nonconformities, observations, and positive findings.
type AuditFinding struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Type of audit finding.
	FindingType AuditFindingType `json:"finding_type,omitempty"`
	// Reference to standard clause.
	ClauseReference *string `json:"clause_reference,omitempty"`
	// Reference to the control (e.g., A.5.1).
	ControlReference *SecurityControlId `json:"control_reference,omitempty"`
	// Description of the finding.
	FindingDescription *string `json:"finding_description,omitempty"`
	// Evidence supporting the finding.
	ObjectiveEvidence *string `json:"objective_evidence,omitempty"`
	// Analysis of root cause.
	RootCauseAnalysis *string `json:"root_cause_analysis,omitempty"`
	// Risk implications of the finding.
	RiskImplication *string `json:"risk_implication,omitempty"`
	// Recommended action to address finding.
	RecommendedAction *string `json:"recommended_action,omitempty"`
	// Response from the auditee.
	AuditeeResponse *string `json:"auditee_response,omitempty"`
	// Corrective action linked to this finding.
	LinkedCorrectiveAction *CorrectiveActionId `json:"linked_corrective_action,omitempty"`
	// Status of finding closure.
	ClosureStatus *string `json:"closure_status,omitempty"`
	// Date the finding was closed.
	ClosureDate *time.Time `json:"closure_date,omitempty"`
}

// A management review per Clause 9.3, conducted by top management to evaluate ongoing ISMS performance and fitness for purpose.
type ManagementReview struct {
	// Embedded types for inheritance
	DocumentedInformation `json:",inline"`
	// Date when the management review was conducted.
	ReviewDate *time.Time `json:"review_date,omitempty"`
	// Attendees of the review.
	Attendees []string `json:"attendees,omitempty"`
	// Status of actions from previous reviews.
	PreviousActionsStatus *string `json:"previous_actions_status,omitempty"`
	// Changes in context since last review.
	ContextChanges *string `json:"context_changes,omitempty"`
	// Changes in interested party requirements.
	InterestedPartyChanges *string `json:"interested_party_changes,omitempty"`
	// Feedback from interested parties considered in the management review.
	InterestedPartyFeedback *string `json:"interested_party_feedback,omitempty"`
	// Trends in information security performance.
	PerformanceTrends *string `json:"performance_trends,omitempty"`
	// Summary of audit results.
	AuditResultsSummary *string `json:"audit_results_summary,omitempty"`
	// Results of risk assessment.
	RiskAssessmentResults *string `json:"risk_assessment_results,omitempty"`
	// Status of the risk treatment plan considered in the management review.
	RiskTreatmentStatus *string `json:"risk_treatment_status,omitempty"`
	// Changes in risks and opportunities considered in the management review, per Clause 9.3.2 f).
	RisksAndOpportunitiesChanges *string `json:"risks_and_opportunities_changes,omitempty"`
	// Opportunities for improvement identified.
	ImprovementOpportunities []string `json:"improvement_opportunities,omitempty"`
	// Decisions made in the review.
	Decisions []string `json:"decisions,omitempty"`
	// Action items from the review.
	ActionItems []string `json:"action_items,omitempty"`
	// Planned date for next review.
	NextReviewDate *time.Time `json:"next_review_date,omitempty"`
}

// A nonconformity identified per Clause 10.2, representing failure to fulfill a requirement.
type Nonconformity struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Source of nonconformity detection.
	NonconformitySource *string `json:"nonconformity_source,omitempty"`
	// Date the nonconformity was detected.
	DetectionDate *time.Time `json:"detection_date,omitempty"`
	// Person or process that detected the nonconformity.
	DetectedBy *string `json:"detected_by,omitempty"`
	// Requirement that was not fulfilled.
	RequirementViolated *string `json:"requirement_violated,omitempty"`
	// Description of the nonconformity.
	NonconformityDescription *string `json:"nonconformity_description,omitempty"`
	// Immediate actions taken to control/correct.
	ImmediateActions []string `json:"immediate_actions,omitempty"`
	// How consequences were dealt with.
	ConsequencesAddressed *string `json:"consequences_addressed,omitempty"`
	// Root cause of the nonconformity.
	RootCause *string `json:"root_cause,omitempty"`
	// Check for similar nonconformities elsewhere.
	SimilarNonconformitiesCheck *string `json:"similar_nonconformities_check,omitempty"`
	// Corrective actions addressing this nonconformity.
	LinkedCorrectiveActions []CorrectiveActionId `json:"linked_corrective_actions,omitempty"`
	// Current status of the document or entity.
	Status *string `json:"status,omitempty"`
	// Date the finding was closed.
	ClosureDate *time.Time `json:"closure_date,omitempty"`
	// Evidence supporting closure.
	ClosureEvidence *string `json:"closure_evidence,omitempty"`
}

// A corrective action per Clause 10.2 to address the root cause of a nonconformity and reduce the likelihood of recurrence.
type CorrectiveAction struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Nonconformity this action addresses.
	LinkedNonconformity *NonconformityId `json:"linked_nonconformity,omitempty"`
	// Description of the action.
	ActionDescription *string `json:"action_description,omitempty"`
	// Root cause this action addresses.
	RootCauseAddressed *string `json:"root_cause_addressed,omitempty"`
	// Party responsible for the activity.
	ResponsibleParty *string `json:"responsible_party,omitempty"`
	// Target date for completing the action.
	TargetCompletionDate *time.Time `json:"target_completion_date,omitempty"`
	// Actual date the action was completed.
	ActualCompletionDate *time.Time `json:"actual_completion_date,omitempty"`
	// Resources required for implementation.
	ResourcesRequired *string `json:"resources_required,omitempty"`
	// Criteria for evaluating effectiveness.
	EffectivenessCriteria *string `json:"effectiveness_criteria,omitempty"`
	// Date effectiveness was reviewed.
	EffectivenessReviewDate *time.Time `json:"effectiveness_review_date,omitempty"`
	// Whether effectiveness was verified.
	EffectivenessVerified *bool `json:"effectiveness_verified,omitempty"`
	// Changes to ISMS required as a result.
	IsmsChangesRequired *string `json:"isms_changes_required,omitempty"`
	// Current status of the document or entity.
	Status *string `json:"status,omitempty"`
}

// An opportunity for continual improvement per Clause 10.1, enhancing overall ISMS performance.
type ImprovementOpportunity struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Source of the improvement opportunity.
	ImprovementSource *string `json:"improvement_source,omitempty"`
	// Date identified.
	IdentificationDate *time.Time `json:"identification_date,omitempty"`
	// Person who identified it.
	IdentifiedBy *string `json:"identified_by,omitempty"`
	// Description of the improvement.
	ImprovementDescription *string `json:"improvement_description,omitempty"`
	// Expected benefit from implementation.
	ExpectedBenefit *string `json:"expected_benefit,omitempty"`
	// Priority level.
	Priority *string `json:"priority,omitempty"`
	// Plan for implementing the improvement.
	ImplementationPlan *string `json:"implementation_plan,omitempty"`
	// Party responsible for the activity.
	ResponsibleParty *string `json:"responsible_party,omitempty"`
	// Target date for achieving the objective.
	TargetDate *time.Time `json:"target_date,omitempty"`
	// Actual date the action was completed.
	ActualCompletionDate *time.Time `json:"actual_completion_date,omitempty"`
	// Assessment of actual outcomes.
	OutcomeAssessment *string `json:"outcome_assessment,omitempty"`
	// Current status of the document or entity.
	Status *string `json:"status,omitempty"`
}

// An information asset or associated asset requiring protection, per Annex A control 5.9.
type Asset struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Type of asset.
	AssetType *string `json:"asset_type,omitempty"`
	// Owner of the asset.
	AssetOwner *string `json:"asset_owner,omitempty"`
	// Custodian responsible for day-to-day protection.
	AssetCustodian *string `json:"asset_custodian,omitempty"`
	// Information classification level.
	Classification *string `json:"classification,omitempty"`
	// Physical or logical location.
	Location *string `json:"location,omitempty"`
	// Criticality rating of the asset.
	Criticality *string `json:"criticality,omitempty"`
	// Associated risks.
	RelatedRisks []RiskId `json:"related_risks,omitempty"`
	// Controls related to this policy.
	ApplicableControls []SecurityControlId `json:"applicable_controls,omitempty"`
}

// An information security event per A.5.25, which may or may not be categorized as an incident.
type InformationSecurityEvent struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Date and time of the event.
	EventDatetime *time.Time `json:"event_datetime,omitempty"`
	// Person who reported the event.
	Reporter *string `json:"reporter,omitempty"`
	// Description of the event.
	EventDescription *string `json:"event_description,omitempty"`
	// Assets affected by this risk or incident.
	AffectedAssets []AssetId `json:"affected_assets,omitempty"`
	// Initial assessment of the event.
	InitialAssessment *string `json:"initial_assessment,omitempty"`
	// Whether the event was categorized as an incident.
	CategorizedAsIncident *bool `json:"categorized_as_incident,omitempty"`
	// Linked incident if categorized.
	LinkedIncident *InformationSecurityIncidentId `json:"linked_incident,omitempty"`
}

// An information security incident per A.5.26, requiring response per documented procedures.
type InformationSecurityIncident struct {
	// Embedded types for inheritance
	NamedEntity `json:",inline"`
	// Date and time the incident occurred or was detected.
	IncidentDatetime *time.Time `json:"incident_datetime,omitempty"`
	// Category of incident.
	IncidentCategory SecurityIncidentCategory `json:"incident_category,omitempty"`
	// Severity rating of the incident.
	Severity RiskLevel `json:"severity,omitempty"`
	// Assets affected by this risk or incident.
	AffectedAssets []AssetId `json:"affected_assets,omitempty"`
	// CIA properties affected by the incident.
	AffectedCia []CIAProperty `json:"affected_cia,omitempty"`
	// Description of the incident.
	IncidentDescription *string `json:"incident_description,omitempty"`
	// How the incident was detected.
	DetectionMethod *string `json:"detection_method,omitempty"`
	// Actions taken in response.
	ResponseActions []string `json:"response_actions,omitempty"`
	// Actions to contain the incident.
	ContainmentActions []string `json:"containment_actions,omitempty"`
	// Actions to eradicate the cause.
	EradicationActions []string `json:"eradication_actions,omitempty"`
	// Actions to recover normal operations.
	RecoveryActions []string `json:"recovery_actions,omitempty"`
	// Root cause of the nonconformity.
	RootCause *string `json:"root_cause,omitempty"`
	// Lessons learned from the incident.
	LessonsLearned []string `json:"lessons_learned,omitempty"`
	// Evidence collected.
	EvidenceCollected []string `json:"evidence_collected,omitempty"`
	// Whether notification to authorities/parties was required.
	NotificationRequired *bool `json:"notification_required,omitempty"`
	// Notifications that were made.
	NotificationsMade []string `json:"notifications_made,omitempty"`
	// Date and time of incident closure.
	ClosureDatetime *time.Time `json:"closure_datetime,omitempty"`
	// Post-incident review findings.
	PostIncidentReview *string `json:"post_incident_review,omitempty"`
}

type OrganizationId string

type InterestedPartyId string

type InformationSecurityPolicyId string

type InformationSecurityObjectiveId string

type RiskAssessmentProcessId string

type RiskTreatmentProcessId string

type StatementOfApplicabilityId string

type SecurityControlId string

type RoleId string

type ResourceId string

type CompetenceRecordId string

type AwarenessProgramId string

type CommunicationPlanId string

type DocumentedInformationId string

type OperationalProcedureId string

type RiskAssessmentId string

type RiskTreatmentPlanId string

type MonitoringProgramId string

type InternalAuditId string

type ManagementReviewId string

type NonconformityId string

type CorrectiveActionId string

type ImprovementOpportunityId string

type TopicSpecificPolicyId string

type RiskId string

type AssetId string

type AuditFindingId string

type InformationSecurityIncidentId string


